//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuzayedeUrunleri
    {
        public int ID { get; set; }
        public int MuzayedeID { get; set; }
        public int UrunID { get; set; }
    }
}
