//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muzayede
    {
        public int MuzayedeID { get; set; }
        public System.TimeSpan Sure { get; set; }
        public System.DateTime MTarih { get; set; }
        public string MuzayedeAdi { get; set; }
        public int KullaniciID { get; set; }
        public int Izlenme { get; set; }
    }
}
