//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisID { get; set; }
        public System.DateTime SiparisTarih { get; set; }
        public decimal SiparisTutari { get; set; }
        public bool SiparisDurum { get; set; }
        public int SiparisDetayID { get; set; }
        public int KullaniciID { get; set; }
    }
}
