//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public int KategoriID { get; set; }
        public int KullaniciID { get; set; }
        public int UrunAdet { get; set; }
        public decimal UrunFiyat { get; set; }
        public string UrunAciklamasi { get; set; }
        public bool UrunDurum { get; set; }
    }
}
